### ISSUE TITLE
Basic example doesn't work:

### ISSUE THREAD

**Issue by wbprice** [krakenjs/levee#15]
When trying the [Levee Basic Example](https://github.com/krakenjs/levee#basic-usage), the following error gets thrown.

```bash
Williams-MacBook-Pro:levee-basic-example blaine$ node index.js
/Users/blaine/Documents/node_modules/wreck/lib/index.js:474
    return this._shortcutWrap('GET', uri, options, callback);
                ^

TypeError: this._shortcutWrap is not a function
    at Object.internals.Client.get [as execute] (/Users/blaine/Documents/node_modules/wreck/lib/index.js:474:17)
    at zalgo (/Users/blaine/Documents/node_modules/levee/lib/zalgo.js:28:12)
    at Breaker._run (/Users/blaine/Documents/node_modules/levee/lib/breaker.js:125:13)
    at Breaker.run (/Users/blaine/Documents/node_modules/levee/lib/breaker.js:60:15)
    at Object.<anonymous> (/Users/blaine/Documents/levee-basic-example/index.js:21:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

I made a quick repo to demonstrate: https://github.com/wbprice/levee-basic-example

**Comment by tlivings** [comment]
If you need a bound function you can pass Levee a bound function. 

Since apparently Wreck has made breaking changes, this example should be updated.
